# Generated by Django 4.2.25 on 2026-03-14 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('target_verb', models.CharField(max_length=100)),
                ('attempt_word', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('infinitive', models.CharField(max_length=100)),
                ('past_tense', models.CharField(max_length=100)),
                ('spanish', models.CharField(max_length=100)),
            ],
        ),
    ]
