# Generated by Django 4.2.29 on 2026-06-15 18:48

from django.db import migrations

def add_ed_verbs(apps, schema_editor):
    Verb = apps.get_model('pastapp', 'Verb')
    ed_verbs = [
        {"group": "ED", "infinitive": "PLAY", "past_tense": "PLAYED", "spanish": "JUGAR"},
        {"group": "ED", "infinitive": "WORK", "past_tense": "WORKED", "spanish": "TRABAJAR"},
        {"group": "ED", "infinitive": "WANT", "past_tense": "WANTED", "spanish": "QUERER"},
        {"group": "ED", "infinitive": "LOOK", "past_tense": "LOOKED", "spanish": "MIRAR"},
        {"group": "ED", "infinitive": "CALL", "past_tense": "CALLED", "spanish": "LLAMAR"},
        {"group": "ED", "infinitive": "ASK", "past_tense": "ASKED", "spanish": "PREGUNTAR"},
        {"group": "ED", "infinitive": "NEED", "past_tense": "NEEDED", "spanish": "NECESITAR"},
        {"group": "ED", "infinitive": "HELP", "past_tense": "HELPED", "spanish": "AYUDAR"},
        {"group": "ED", "infinitive": "TALK", "past_tense": "TALKED", "spanish": "HABLAR"},
        {"group": "ED", "infinitive": "TURN", "past_tense": "TURNED", "spanish": "GIRAR"},
        {"group": "ED", "infinitive": "START", "past_tense": "STARTED", "spanish": "COMENZAR"},
        {"group": "ED", "infinitive": "SHOW", "past_tense": "SHOWED", "spanish": "MOSTRAR"},
        {"group": "ED", "infinitive": "TRY", "past_tense": "TRIED", "spanish": "INTENTAR"},
        {"group": "ED", "infinitive": "MOVE", "past_tense": "MOVED", "spanish": "MOVER"},
        {"group": "ED", "infinitive": "LIVE", "past_tense": "LIVED", "spanish": "VIVIR"},
        {"group": "ED", "infinitive": "BELIEVE", "past_tense": "BELIEVED", "spanish": "CREER"},
        {"group": "ED", "infinitive": "HAPPEN", "past_tense": "HAPPENED", "spanish": "SUCEDER"},
        {"group": "ED", "infinitive": "REMEMBER", "past_tense": "REMEMBERED", "spanish": "RECORDAR"},
        {"group": "ED", "infinitive": "STUDY", "past_tense": "STUDIED", "spanish": "ESTUDIAR"},
        {"group": "ED", "infinitive": "WALK", "past_tense": "WALKED", "spanish": "CAMINAR"},
        {"group": "ED", "infinitive": "WAIT", "past_tense": "WAITED", "spanish": "ESPERAR"},
        {"group": "ED", "infinitive": "WATCH", "past_tense": "WATCHED", "spanish": "OBSERVAR"},
        {"group": "ED", "infinitive": "STOP", "past_tense": "STOPPED", "spanish": "DETENER"},
        {"group": "ED", "infinitive": "OPEN", "past_tense": "OPENED", "spanish": "ABRIR"},
        {"group": "ED", "infinitive": "CLOSE", "past_tense": "CLOSED", "spanish": "CERRAR"},
    ]
    for v in ed_verbs:
        Verb.objects.get_or_create(
            infinitive=v['infinitive'],
            defaults={
                'group': v['group'],
                'past_tense': v['past_tense'],
                'spanish': v['spanish']
            }
        )

def remove_ed_verbs(apps, schema_editor):
    Verb = apps.get_model('pastapp', 'Verb')
    Verb.objects.filter(group="ED").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pastapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ed_verbs, remove_ed_verbs),
    ]
