# Generated by Django 4.2.25 on 2026-06-24 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastapp', '0002_add_ed_verbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushUpGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.IntegerField(default=100)),
                ('weekly', models.IntegerField(default=500)),
                ('monthly', models.IntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PushUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
